---
openshift_cluster_content:
- object: projectrequest
  content:
  - name: basic-python-flask-spaces
    file: "{{ inventory_dir }}/../files/projects/projects.yml"
    file_action: create
- object: imagestream
  content:
  - name: jenkins-slave-python
    file: "{{ inventory_dir }}/../files/imagestreams/imagestreams.yml"
    namespace: basic-python-flask-build
- object: deployments
  content:
  - name: jenkins
    namespace: basic-python-flask-build
    template: "{{ inventory_dir }}/../files/deployments/jenkins.yml"
    params: "{{ inventory_dir }}/../files/deployments/build/params"
  - name: basic-python-flask-dev
    template: "{{ inventory_dir }}/../files/deployments/template.yml"
    params: "{{ inventory_dir }}/../files/deployments/dev/params"
  - name: basic-python-flask-stage
    template: "{{ inventory_dir }}/../files/deployments/template.yml"
    params: "{{ inventory_dir }}/../files/deployments/stage/params"
  - name: basic-python-flask-prod
    template: "{{ inventory_dir }}/../files/deployments/template.yml"
    params: "{{ inventory_dir }}/../files/deployments/prod/params"
- object: builds
  content:
  - name: jenkins
    template: "{{ inventory_dir }}/../files/builds/template.yml"
    params: "{{ inventory_dir }}/../files/builds/dev/params"
