apiVersion: v1
kind: Template
labels:
  template: jenkins-slave
metadata:
  annotations:
    description: Template for Jenkins slave
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: jenkins-slave
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      application: ${SLAVE_NAME}
    name: ${SLAVE_NAME}
    namespace: ${NAMESPACE}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${SLAVE_NAME}:latest
    source:
      type: Git
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: ${CONTEXT_DIR}
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: ${JENKINS_IMAGE}
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      slave-label: python
    labels:
      application: ${SLAVE_NAME}
      role: jenkins-slave
    name: ${SLAVE_NAME}
    namespace: ${NAMESPACE}
parameters:
- description: The name for the application.
  name: SLAVE_NAME
  required: true
- description: The namespace to deploy into
  name: NAMESPACE
  required: true
- description: Git source URL for application
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/pabrahamsson/jenkins.git
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: master
- description: Path within Git repository to build; empty for root of repository
  name: CONTEXT_DIR
  value:
- description: The Jenkins source image
  name: JENKINS_IMAGE
  required: true
  value: openshift/jenkins-slave-base-centos7
